config/routes.rb
Rails.application.routes.draw do
devise_for :users
root to: 'homes#top'
get 'home/about' => 'homes#about'
resources :books,only: [:create, :index, :show, :destroy,:update,:edit]do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create,:destroy]
end
resources :users, only: [:show, :edit,:create,:index,:update]
get "search_tag" => "searches#search_tag"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :star, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  validates :title ,presence: true
  validates :tag ,presence: true
  validates :body ,presence: true ,length: {maximum: 200}
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  scope :day, -> {order(created_at: :desc)}
  scope :star, ->{order(star: :desc)}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user

  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true
  has_one_attached :image
  def group_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :body,length: { in: 1..140 } 
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  # DM機能
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # 閲覧数機能
  has_many :view_counts, dependent: :destroy
    # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  validates :introduction ,length: {maximum: 50}
  validates :name ,uniqueness: true ,length: {minimum: 2,maximum: 20}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
    if params[:sort] == "day"
      @books = Book.day
    elsif params[:sort] == "star"
      @books = Book.star
    else
      @books = Book.all
    end
    @book = Book.new
    @user = current_user
  end

  def show
    @book_comment = BookComment.new
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id!=current_user.id
      redirect_to books_path
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id),notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book),notice:"You have updated book successfully."
    else
      render :edit
    end
  end
  private

  def book_params
    params.require(:book).permit(:title, :body,:star, :tag)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def show
        @user=User.find(params[:id])
        @books=@user.books
        @book = Book.new
        @today_book = @books.created_today
        @yesterday_book = @books.created_yesterday
        @this_week_book = @books.created_this_week
        @last_week_book = @books.created_last_week
    end

    def index
        @user=current_user
        @users=User.all
        @book = Book.new
    end

    def search
        @user = User.find(params[:user_id])
        @books = @user.books 
        @book = Book.new
        if params[:created_at] == ""
          @search_book = "日付を選択してください"
        else
          create_at = params[:created_at]
          @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to user_path(@user.id),notice:"You have updated user successfully."
        else
          render :edit
        end
    end

    def edit
        @user=User.find(params[:id])
        if @user.id!=current_user.id
            redirect_to user_path(current_user.id)
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :profile_image,:introduction)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_search.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr> 
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/_userinfo.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(63,63) %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
        <th>name</th>
        <th><%= user.name %></th>
    </tr>
    <tr>
        <th>introduction</th>
        <th><%= user.introduction%></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%= link_to user.followings.count, user_followings_path(user) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.followers.count, user_followers_path(user) %></th>
    </tr>
  </tbody>
</table>

<div class="row">
  <% if current_user != user %>
    <%= render "relationships/btn", user: user %>
    <% if (current_user.following? @user) && (@user.following? current_user)  %>
      <% if @isRoom == true %>
        <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a>
      <% else %>
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, value: @user.id %>
          <% end %>
          <%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to edit_user_path(user),class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <%end%>
</div>

app/views/users/edit.html.erb
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <div id="error_explanation">
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <label for="inputName">Name</label>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name",class:"form-control name"%>
          </div>

          <div class="form-group">
            <label for="user_name">Image</label>
            <%= f.file_field :profile_image, accept: "image/*" %>
          </div>


          <div class="form-group">
            <label for="inputIntroduction">Introduction</label>
            <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction",class:"form-control introduction"%>
          </div>

          <div class="form-group">
            <%= f.submit "Update User",class:"btn btn-secondary"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
        <%= render "userinfo",user:@user%>
        <%= render "books/form",book:@book%>
    </div>
    <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
        <table class="table table-hover table-inverse">
        <thead>
            <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user|%>
                <tr>
                    <td>
                        <%= link_to user_path(user) do %>
                            <%= image_tag user.get_profile_image(40,48) %>
                        <%end%>
                    </td>
                    <td>
                        <%= user.name%>
                    </td>
                    <td>
                        <%= link_to "Show",user_path(user) %>
                    </td>
                </tr>
            <% end %>
        </tbody>
        </table>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
        <%= render "userinfo",user:@user%>
        <%= render "books/form",book:@book%>
    </div>
    <div class="col-md-8 offset-md-1">
        <%= render "books/index",books:@books%>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @today_book.count %></td>
            <td><%= @yesterday_book.count %></td>
            <td>
              <% if @yesterday_book.count == 0 %>
                前日の投稿はありません
              <% else %>
              　<% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
              　<%= (@the_day_before * 100).round %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @this_week_book.count %></td>
            <td><%= @last_week_book.count %></td>
            <td>
              <% if @last_week_book.count == 0 %>
                前週の投稿はありません
              <% else %>
              　<% @the_week_before =   @this_week_book.count / @last_week_book.count.to_f  %>
              　<%= (@the_week_before * 100).round %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <table class="table table-bordered">
        <thead>
          <tr>
          <th>6日前</th>
          <th>5日前</th>
          <th>4日前</th>
          <th>3日前</th>
          <th>1日前</th>
          <th>昨日</th>
          <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
          <th><%= @books.created_6days.count %></th>
          <th><%= @books.created_5days.count %></th>
          <th><%= @books.created_4days.count %></th>
          <th><%= @books.created_3days.count %></th>
          <th><%= @books.created_2days.count %></th>
          <th><%= @yesterday_book.count %></th>
          <th><%= @today_book.count %></th>
          </tr>
        </tbody>
      </table>
<canvas id="myChart"></canvas>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
        datasets: [{
            label: '一週間の投稿推移',
            data: [<%= @books.created_6days.count %>, <%= @books.created_5days.count %>, <%= @books.created_4days.count %>, <%= @books.created_3days.count %>, <%= @books.created_2days.count %>, <%= @yesterday_book.count %>, <%= @today_book.count%>],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          scales: {
            yAxes: [{
              ticks: {
                suggestedMax: 10,
                suggestedMin: 0,
                stepSize: 1,
                callback: function(value, index, values){
                  return  value
                }
              }
            }]
          },
        }
});
</script>
      <%= form_with url: user_search_path(@user),local: false, method: :get  do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class: 'btn btn-primary'  %>
      <% end %>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>
    </div>
  </div>
</div>