config/routes.rb
Rails.application.routes.draw do
devise_for :users
root to: 'homes#top'
get 'home/about' => 'homes#about'
resources :books,only: [:create, :index, :show, :destroy,:update,:edit]do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create,:destroy]
end
resources :users, only: [:show, :edit,:create,:index,:update]
get "search_tag" => "searches#search_tag"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :star, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  validates :title ,presence: true
  validates :tag ,presence: true
  validates :body ,presence: true ,length: {maximum: 200}
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  scope :day, -> {order(created_at: :desc)}
  scope :star, ->{order(star: :desc)}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user

  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true
  has_one_attached :image
  def group_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :body,length: { in: 1..140 } 
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  # DM機能
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # 閲覧数機能
  has_many :view_counts, dependent: :destroy
    # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  validates :introduction ,length: {maximum: 50}
  validates :name ,uniqueness: true ,length: {minimum: 2,maximum: 20}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
    if params[:sort] == "day"
      @books = Book.day
    elsif params[:sort] == "star"
      @books = Book.star
    else
      @books = Book.all
    end
    @book = Book.new
    @user = current_user
  end

  def show
    @book_comment = BookComment.new
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id!=current_user.id
      redirect_to books_path
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id),notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book),notice:"You have updated book successfully."
    else
      render :edit
    end
  end
  private

  def book_params
    params.require(:book).permit(:title, :body,:star, :tag)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>
    <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title ,class:"form-control book_title"%>
    </div>
    <div class="form-group">
    <label for="book_body">Opinion</label>
    <%= f.text_area :body,class:"form-control book_body"%>
    </div>
    <div class="form-group">
    <label for="book_tag">Tag</label>
    <%= f.text_field :tag ,class:"form-control book_tag"%>
    </div>
    <div class="form-group row" id="star">
    <%= f.label :star,'評価 ', class:'col-md-3 col-form-label' %>
    <%= f.hidden_field :star, id: :review_star %>
    </div>
    <div class="form-group">
    <%= f.submit 'Create Book' ,class:"btn btn-success"%>
    </div>
  <script>
  $('#star').raty({
    size     : 20,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    scoreName: 'book[star]',
    half: false,
  });
  </script>
<% end %>

app/views/books/_index.html.erb
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book|%>
        <tr>
            <td>
                <%= link_to user_path(book.user) do %>
                    <%= image_tag book.user.get_profile_image(40,48) %>
                <%end%>
            </td>
            <td>
                <%= link_to book.title ,book_path(book)%>
            </td>
            <td>
              <%= book.body%>
            </td>
            <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book_id: book.id),class: "like" ,method: :delete do %>
                    <i class="fas fa-heart like"></i><%= book.favorites.count%>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book_id: book.id), method: :post do %>
                    <i class="fas fa-heart unlike"></i><%= book.favorites.count %>
                  <% end %>
                <% end %>
            </td>
              <td>閲覧数: <%= book.view_counts.count %></td>
            </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
  <p id="notice"></p>
  <div class="container">
  　<div class="row">
    　<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  　   <h1>Editing Book</h1>
        <div id="error_explanation">
          <% if @book.errors.any? %>
            <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
      <%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title ,class:"form-control book_title"%>
        </div>

        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body ,class:"form-control book_body"%>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book',class:"btn btn-success"%>
        </div>
      <% end %>
      <%=link_to "Show" ,book_path(@book.id)%>
       |
      <%=link_to "Back" ,books_path%>
    　</div>
    </div>
  </div>

app/views/books/index.html.erb
<div id="error_explanation">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
        <%= render "users/userinfo",user:@user%>
        <%= render "form",book:@book%>
    </div>
    <div class="col-md-8 offset-md-1">
        <%= render "index",books:@books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
        <%= render "users/userinfo",user:@user%>
        <%= render "form",book:@new_book%>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= image_tag @user.get_profile_image(63,63) %>
                <br><%= @user.name %>
              <% end %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <td>閲覧数: <%= @book.view_counts.count %></td>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book),class:"btn btn-sm btn-success"%></td>
              <td><%= link_to "Destroy", book_path(@book),method: :delete,class:"btn btn-sm btn-danger", data: { confirm: '本当に消しますか' }%></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    　<h2>Comments</h2>
    　<table class="table">
    　   <tbody>
          <% @book.book_comments.each do |book_comment| %>
            <tr>
              <td>
                <%= link_to user_path(book_comment.user.id) do %>
                  <%= image_tag book_comment.user.get_profile_image(63,63) %>
                <% end %>
              </td>
              <td><%= book_comment.user.name %></td>
              <td><%= book_comment.comment %></td>
              <td>
                <% if book_comment.user == current_user %>
                  <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete ,class:"btn btn-sm btn-danger", data: { confirm: '本当に消しますか' }%>
                <% end %>
              </td>
              <td><%= @book.title %></td>
              <td><%= @book.body %></td>
              <% if @book.user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book),class:"btn btn-sm btn-success"%></td>
                <td><%= link_to "Destroy", book_path(@book),method: :delete,class:"btn btn-sm btn-danger", data: { confirm: '本当に消しますか' }%></td>
              <% end %>
              <td>
                  <% if @book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(book_id: @book.id),class: "like" ,method: :delete do %>
                      <i class="fas fa-heart like"></i><%= @book.favorites.count%>
                    <% end %>
                  <% else %>
                    <%= link_to book_favorites_path(book_id: @book.id), method: :post do %>
                      <i class="fas fa-heart unlike"></i><%= @book.favorites.count %>
                    <% end %>
                  <% end %>
              </td>
              <td></td>
            </tr>
          <% end %>
    　   </tbody>
    　</table>
      <h2>New Comment</h2>
      <% if @error_comment.present? %>
      <div id="error_explanation">
        <% if @error_comment.errors.any? %>
          <h3><%= @error_comment.errors.count %> error prohibited this obj from being saved:</h3>
          <ul>
            <% @error_comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <% end %>
      <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
        <div class="form-group"><%= f.text_area :comment,placeholder: "コメントをここに",class:"form-control" %></div>
        <div class="form-group"><%= f.submit "送信",class:"btn btn-success"%></div>
      <% end %>

    </div>
  </div>
</div>