config/routes.rb
Rails.application.routes.draw do
devise_for :users
root to: 'homes#top'
get 'home/about' => 'homes#about'
resources :books,only: [:create, :index, :show, :destroy,:update,:edit]do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create,:destroy]
end
resources :users, only: [:show, :edit,:create,:index,:update]
get "search_tag" => "searches#search_tag"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :star, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  validates :title ,presence: true
  validates :tag ,presence: true
  validates :body ,presence: true ,length: {maximum: 200}
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  scope :day, -> {order(created_at: :desc)}
  scope :star, ->{order(star: :desc)}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user

  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true
  has_one_attached :image
  def group_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :body,length: { in: 1..140 } 
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  # DM機能
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # 閲覧数機能
  has_many :view_counts, dependent: :destroy
    # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  validates :introduction ,length: {maximum: 50}
  validates :name ,uniqueness: true ,length: {minimum: 2,maximum: 20}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="search_form">
              <%= form_with url: search_tag_path, local: true, method: :get do |f| %>
                <%= f.text_field :tag %>
                <%= f.submit "検索", class: "btn btn-primary" %>
              <% end %>
            </div>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id),class:"nav-link text-light" do%>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path ,class:"nav-link text-light" do%>
                    <i class="fas fa-users"></i>Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path ,class:"nav-link text-light" do %>
                    <i class="fas fa-book-open"></i>Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete ,class:"nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt"></i>Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path,class:"nav-link text-light" do %>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <li>
                  <%= link_to home_about_path,class:"nav-link text-light" do %>
                    <i class="fas fa-link"></i>About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path,class:"nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i>Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path,class:"nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i>Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
    <% end %>
    <%= yield %>
    <footer>
      <div class="container mt-5">
  	    <div class="row">
          <div class="mx-auto">
    		    <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>